version: "3.8"
services:
  db:
    container_name: pg_container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sqlCourse_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  sqlCourse_db:
  pgadmin4_container:
